# Generated by Django 4.1.5 on 2023-01-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wcapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_parser', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_online', models.CharField(max_length=255)),
            ],
        ),
    ]
