# Generated by Django 4.1.5 on 2023-01-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcapi',
            name='last_online',
            field=models.CharField(default='off', max_length=255),
        ),
    ]
