# Generated by Django 4.1.5 on 2023-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0003_history_settings_statistics_delete_wcapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
